### ISSUE TITLE
service.export() refactor

### ISSUE THREAD

**Issue by brookisme** [wri/glad_clusters#4]
Having a method that is close to 200 lines of code is probably a sign some refactoring should be done.  

https://github.com/wri/glad_clusters/blob/master/glad_clusters/utils/service.py#L387-L577

There is an easy fix here.  Create a module that contains the SQL format strings so, for example, https://github.com/wri/glad_clusters/blob/master/glad_clusters/utils/service.py#L518-L563 
can become 
```python
from utils.sql import SOME_SQL_STR
sql = SOME_SQL_STR.format(pg_table, filename)
```
In principal `utils.sql` should contain not only the two big ones but for symmetry you should include the small ones too -  `"DELETE FROM {}` and `SELECT * FROM {} LIMIT 1`.
 
That alone would be a big win.  But while you are at it  the message printed on line 572 that is associated with `SOME_SQL_STR` above could become `SOME_SQL_STR_MSG` or something like that. 

Finally - there could be some more interesting refactoring where a lot of the sql query logic and execution can gets put into various methods that live in `utils.sql`.   

Lets at least do the super quick refactor of moving the sql strings and the sql-message strings to a different file, and if you have the time and good ideas to move some of the sql methods there too that would be great.

**Comment by thomas-maschler** [comment]
fixed in #5
